### ISSUE TITLE
Dont use keyring on linux

### ISSUE THREAD

**Issue by volllly** [fiskaltrust/middleware-launcher#152]
Because of the problems we've encountered in #100 we've decided to remove the functionality of encrypting data at rest with the keyring. We will only support the legacy method for now.

## Tasks

- [x] Remove Keyring Dataprotection related code
- [x] Always use fallback on linux
- [x] Deprecate `useLegacyDataProtection` parameter (print warning that it'll be removed in a future version when it is used in the config or from the cli)
