### ISSUE TITLE
Improve fault tolerance of dataprotection

### ISSUE THREAD

**Issue by volllly** [fiskaltrust/middleware-launcher#153]
When the dataprotection mechanism fails the launcher should be able to recover instead of crashing.

## Tasks

- [x] When the [`client-{cashboxId}.ecdh` curve can not be loaded](https://github.com/fiskaltrust/middleware-launcher/blob/main/src/fiskaltrust.Launcher/Commands/Common.cs#L232) print a warning, regenerate it and redownload the cashbox configuration.
   - [x] If necessary reflect these changes in the [`DoctorCommand`](https://github.com/fiskaltrust/middleware-launcher/blob/main/src/fiskaltrust.Launcher/Commands/DoctorCommand.cs#L89) so it does still work.
- [x] If the `LauncherConfiguration` can not be decrypted (e.g. the proxy string) set the values to null internally and print a Warning suggesting the use of the `config set` command to add the value to the configuration.

**Comment by pawelvds** [comment]
1. I am going to extend description/make it clearier after planning/refinement
2. Implement it
