### ISSUE TITLE
Add readme to released zip file

### ISSUE THREAD

**Issue by volllly** [fiskaltrust/middleware-launcher#157]
# Feature

Add the [README.md](https://github.com/fiskaltrust/middleware-launcher/blob/main/README.md) file to the `.zip` file containing the `fiskaltrust.Launcher` that can be downloaded from the portal or github releases.

# Tasks
- [x] Adapt README to work as a single markdownfile (links should be absolute http links and images should be in there as base64 strings (https://stackoverflow.com/a/50817623)).
- [x] Add markdown templating system to cut out stuff that is not interesting (e.g the Contrubuting and licence sections).
- [x] Add README to scripts artifact
